//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Department_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> MaDH { get; set; }
    }
}
